### ISSUE TITLE
${file()} imports

### ISSUE THREAD

**Issue by ebisbe** [zirkelc/serverless-esm-ts#1]
Hey! 

I'm wondering how I can do:

```
environment: {
	AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
	NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
	plans: '${file(serverless.conf.js):premiumPlans}'
},
```

where serverless.conf.js is:

```
export const premiumPlans = ['1', '2']
```
I keep getting 

Cannot resolve variable at "provider.environment.plans": Cannot load "serverless.conf.js": Initialization error: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/enricu/Development/skedr/serverless-esm-ts/serverless.conf.js from /Users/enricu/Development/skedr/serverless-esm-ts/node_modules/serverless/lib/configuration/variables/sources/file.js not supported.

**Comment by zirkelc** [comment]
Could you share a repo, so I can debug it locally?

You could try to change the extension to `.mjs` so that Serverless uses `import()` instead of `require()`, or try it the other way around by using `.cjs`.

**Comment by ebisbe** [comment]
Sorry I was digging for myself and found a solution. I can use the file as `.cjs`. And now I see your answer will try if it works with `.mjs`. 
I've also noticed that we don't need to use the --config param. In the last version 3.38 it uses automatically the `.cjs` file.

**Comment by ebisbe** [comment]
The `.mjs` option is not working. I understand that if you have `module` type in the package then all js files are treated as `mjs` files right? Because if that's right then it wasn't working from the beginnig and `${file()}` function only works with common js modules. 

At least now is almost everything in the same format....

**Comment by zirkelc** [comment]
> I've also noticed that we don't need to use the --config param. In the last version 3.38 it uses automatically the `.cjs` file.

I didn't check the latest source code, but the last time I checked the `.ts` extension has precedence over `.js`: 

https://github.com/serverless/serverless/blob/ed111e021b286eb4a68f9b2fce7fb641e03340bd/lib/configuration/read.js#L83-L168

That's the reason I explicitly included the config param, because they can always change the order in which the config is being resolved.

> The `.mjs` option is not working. I understand that if you have `module` type in the package then all js files are treated as `mjs` files right? Because if that's right then it wasn't working from the beginnig and `${file()}` function only works with common js modules.

It is always a bit tricky to get it right. It depends if Serverless uses import() or require() to resolve the `${file()}` variable. I assume they use require(), because your serverless config is .cjs which makes it a CJS, but your project is ESM so every file is considered an ESM. Therefore, you have to rely on explicit file extension to use the right way to import the file.

**Comment by ebisbe** [comment]
oh, Interesting that switch case. I guess the worst is that a deploy fails and I spend 2-3h remember why now is failing... I'll add that line just in case. 

> Therefore, you have to rely on explicit file extension to use the right way to import the file.

I'm find with that. It's just one file. If I can refactor all my scripts to work with ESM a nothing strange happens then it all will be worth it for me. 

Thanks for all the inputs and help!
